### ISSUE TITLE
Cannot clone repository due to missing cloudfront credentials (git lfs)

### ISSUE THREAD

**Issue by zhad3** [o3de/ThirdPersonTemplate#1]
I wanted to use this sample project as a first glimpse to test out O3DE but sadly it didn't work out as I had hoped...

Are there some guest or anonymous credentials that are usable or is this intended? If so maybe it would be nice to mention that in the README.

![00](https://user-images.githubusercontent.com/6462844/197585643-fe1ffa96-c150-4134-9344-6e48376ad8c4.png)
![01](https://user-images.githubusercontent.com/6462844/197585658-31a2e867-3e4c-45e3-9373-e37ec0cff0ec.png)
![02](https://user-images.githubusercontent.com/6462844/197585666-3105de46-7bea-42bd-8c12-c3c47be7991f.png)

```powershell
PS> git lfs pull
batch response: Forbidden  0% (0/1), 0 B | 0 B/s
error: failed to fetch some objects from 'https://d3qwk2s0ms2a5b.cloudfront.net/api/v1'
```

**Comment by cdomingo** [comment]
So sorry for this oversight @zhad3! You actually use your own GitHub credentials to pull the assets. You will need a personal access token set up to do so (see: https://www.o3de.org/docs/welcome-guide/setup/setup-from-github/#configure-credentials-for-git-lfs)

Thank you for flagging this - I will make sure to update the ReadMe to avoid future confusion.

**Comment by zhad3** [comment]
I did try my git credentials but the key was to use an access token instead as "password". I was now able to successfully clone the repo. Thank you for your help and quick response @cdomingo !
